create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = timezone('utc', now());
    return new;
end;
$$;

create table if not exists public.departments (
    id integer generated by default as identity primary key,
    name varchar(100) not null,
    description text null,
    head_member_id integer null,
    bank_name varchar(120) null,
    account_name varchar(120) null,
    account_number varchar(80) null,
    bank_branch varchar(120) null,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.clusters (
    id integer generated by default as identity primary key,
    name varchar(100) not null,
    location varchar(255) null,
    description text null,
    leader_id integer null,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.users (
    id integer generated by default as identity primary key,
    name varchar(100) not null,
    email varchar(100) not null unique,
    username varchar(60) null,
    password varchar(255) not null,
    role varchar(30) null default 'staff',
    photo_path varchar(255) null,
    department_id integer null references public.departments(id) on delete set null,
    last_login timestamptz null,
    reset_token_hash varchar(64) null,
    reset_token_expires_at timestamptz null,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.members (
    id integer generated by default as identity primary key,
    member_code varchar(20) null unique,
    bio_id varchar(50) null unique,
    first_name varchar(50) not null,
    last_name varchar(50) not null,
    email varchar(100) null,
    phone varchar(20) null,
    nationality varchar(100) null,
    address text null,
    stays_at varchar(255) null,
    home_town varchar(120) null,
    date_of_birth date null,
    gender varchar(20) null,
    marital_status varchar(20) null,
    spouse_name varchar(150) null,
    mother_name varchar(150) null,
    father_name varchar(150) null,
    is_baptized boolean not null default false,
    baptism_pastor_church varchar(255) null,
    currently_working boolean not null default false,
    work_name varchar(150) null,
    occupation varchar(100) null,
    position varchar(100) null,
    cluster_id integer null references public.clusters(id) on delete set null,
    department_id integer null references public.departments(id) on delete set null,
    membership_status varchar(40) null default 'Active',
    join_date date null,
    baptism_date date null,
    photo_path varchar(255) null,
    emergency_contact_name varchar(100) null,
    emergency_contact_phone varchar(20) null,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.member_departments (
    member_id integer not null references public.members(id) on delete cascade,
    department_id integer not null references public.departments(id) on delete cascade,
    created_at timestamptz not null default timezone('utc', now()),
    primary key (member_id, department_id)
);

create index if not exists idx_member_departments_department
    on public.member_departments (department_id);

create table if not exists public.visitors (
    id integer generated by default as identity primary key,
    first_name varchar(50) not null,
    last_name varchar(50) not null,
    phone varchar(20) null,
    email varchar(100) null,
    gender varchar(20) null,
    address text null,
    visit_date date null,
    service_attended varchar(100) null,
    is_first_time boolean not null default true,
    invited_by varchar(100) null,
    preferred_contact_method varchar(30) null,
    prayer_request text null,
    follow_up_status varchar(30) not null default 'Pending',
    follow_up_date date null,
    follow_up_notes text null,
    assigned_to integer null references public.users(id) on delete set null,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.attendance (
    id integer generated by default as identity primary key,
    member_id integer null references public.members(id) on delete cascade,
    service_date date null,
    service_type varchar(50) null,
    status varchar(20) not null default 'Present',
    check_in_time timestamptz not null default timezone('utc', now()),
    qr_code_scanned boolean not null default false
);

create table if not exists public.finances (
    id integer generated by default as identity primary key,
    member_id integer null references public.members(id) on delete set null,
    transaction_type varchar(100) null,
    amount numeric(15, 2) not null,
    payment_method varchar(50) null,
    transaction_date date null,
    description text null,
    category varchar(100) null,
    subcategory varchar(100) null,
    reference_no varchar(100) null,
    recorded_by integer null references public.users(id) on delete set null,
    created_at timestamptz not null default timezone('utc', now()),
    department_id integer null references public.departments(id) on delete set null,
    transaction_number varchar(50) null unique
);

create table if not exists public.equipment (
    id integer generated by default as identity primary key,
    item_name varchar(100) not null,
    category varchar(50) null,
    serial_number varchar(100) null,
    purchase_date date null,
    cost numeric(15, 2) null,
    condition_status varchar(20) null,
    assigned_to_department integer null references public.departments(id) on delete set null,
    last_maintained date null,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.settings (
    id integer generated by default as identity primary key,
    key_name varchar(255) not null unique,
    value text null,
    description text null,
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.audit_logs (
    id integer generated by default as identity primary key,
    user_id integer null references public.users(id) on delete set null,
    action varchar(255) not null,
    entity_type varchar(100) null,
    entity_id integer null,
    old_values jsonb null,
    new_values jsonb null,
    ip_address varchar(45) null,
    user_agent text null,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_members_department_id on public.members (department_id);
create index if not exists idx_members_cluster_id on public.members (cluster_id);
create index if not exists idx_members_join_date on public.members (join_date);
create index if not exists idx_members_birth_date on public.members (date_of_birth);
create index if not exists idx_finances_member_id on public.finances (member_id);
create index if not exists idx_finances_department_id on public.finances (department_id);
create index if not exists idx_finances_transaction_date on public.finances (transaction_date);
create index if not exists idx_attendance_member_id on public.attendance (member_id);
create index if not exists idx_attendance_service_date on public.attendance (service_date);
create index if not exists idx_users_username on public.users (username);
create index if not exists idx_users_department_id on public.users (department_id);

drop trigger if exists trg_users_updated_at on public.users;
create trigger trg_users_updated_at
before update on public.users
for each row
execute function public.set_updated_at();

drop trigger if exists trg_members_updated_at on public.members;
create trigger trg_members_updated_at
before update on public.members
for each row
execute function public.set_updated_at();

drop trigger if exists trg_settings_updated_at on public.settings;
create trigger trg_settings_updated_at
before update on public.settings
for each row
execute function public.set_updated_at();

insert into public.settings (key_name, value, description)
values
    ('church_name', 'UPPER ROOM ASSEMBLY MAMPONG', 'Church display name'),
    ('church_logo', '', 'Church logo relative path'),
    ('theme', 'dark', 'Application theme'),
    ('finance_currency', 'GHS', 'Default finance currency'),
    ('sms_provider', 'infobip', 'Primary SMS gateway provider'),
    ('sms_sender_id', 'UPPERROOM', 'Default SMS sender identifier'),
    ('sms_infobip_base_url', 'https://api.infobip.com', 'Infobip API base URL')
on conflict (key_name) do nothing;

insert into public.users (name, email, username, password, role)
values (
    'System Admin',
    'ranchoyc2019@gmail.com',
    'admin',
    '$2y$10$xV1vI38M72FjyY1/q5ZrX.QT.Wgv4GK76aSki0uhJeh8FCxYuLAVG',
    'admin'
)
on conflict (email) do nothing;
